name: ci test
on: push
jobs:
  defaults:
    run:
      working-directory: src
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: build test
        run: yarn build
